name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check HTML file
        run: |
          echo "CI Started"
          test -f index.html && echo "File exists"
          echo "CI Successful"

           - name: Slack Notification
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"âœ… SUCCESS: CI passed for devops-webapp on branch main."}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
